### ISSUE TITLE
OutputViewExt#waitUntilContainsText is unstable

### ISSUE THREAD

**Issue by mlorinc** [djelinek/vscode-uitests-tooling#19]
`OutputViewExt#waitUntilContainsText` method fails when output is not clickable and throws following exception: 

`WebDriverError: element click intercepted: Element <textarea data-mprt="6" class="inputarea" wrap="off" autocorrect="off" autocapitalize="off" autocomplete="off" spellcheck="false" aria-label="The editor is not accessible at this time. Press Alt+F1 for options." role="textbox" aria-multiline="true" aria-haspopup="false" aria-autocomplete="both" style="font-family: &quot;Droid Sans Mono&quot;, monospace, monospace, &quot;Droid Sans Fallback&quot;; font-weight: normal; font-size: 14px; font-feature-settings: &quot;liga&quot; 0, &quot;calt&quot; 0; line-height: 19px; letter-spacing: 0px; top: 0px; left: 0px; width: 1px; height: 1px;"></textarea> is not clickable at point (303, 525). Other element would receive the click: <div class="monaco-sash vertical" style="left: 301px;"></div>`

**Comment by djelinek** [comment]
closing - moved to https://issues.redhat.com/browse/FUSETOOLS2-285
