### ISSUE TITLE
Tag version 2.0.2 as well?

### ISSUE THREAD

**Issue by dcermak** [djelinek/vscode-uitests-tooling#36]
It looks like the latest package version on npm is 2.0.2 but this version has not been tagged on github. I guess that would be commit https://github.com/djelinek/vscode-uitests-tooling/commit/21634dd98befc50ebb1edcd8b328000603c5520c? Could you maybe tag here as well for completeness?

**Comment by djelinek** [comment]
Hi, yes you are right :-) Thank you for reminder!

the latest tag should be now available.
