### ISSUE TITLE
Remove dependency on vscode-extension-tester-native which is deprecated

### ISSUE THREAD

**Issue by apupier** [djelinek/vscode-uitests-tooling#44]
see https://github.com/redhat-developer/vscode-extension-tester/issues/396#issuecomment-979056859 and https://github.com/redhat-developer/vscode-extension-tester/blob/master/CHANGELOG.md#420-sep-3

**Comment by apupier** [comment]
@jrichter Can you provide guidance on how to remove it from this library please?
it is used in https://github.com/djelinek/vscode-uitests-tooling/blob/master/src/components/Dialog.ts

**Comment by apupier** [comment]
In the wiki, it is still mentioning to use the native API https://github.com/redhat-developer/vscode-extension-tester/wiki/OpenDialog (I added a deprecated warning but woudl be nice habing mor einformation how to migrate

**Comment by mlorinc** [comment]
There is implemented modern solution in [InputBoxOpenDialogs.ts](https://github.com/djelinek/vscode-uitests-tooling/blob/master/src/components/dialog/InputBoxOpenDialogs.ts) but it might need some stabilization. In regard of native dialogs I will bring this topic in upcoming 1on1 with @djelinek.

**Comment by apupier** [comment]
fixed in 2.2.1 release
